### ISSUE TITLE
Поддержка php8.0

### ISSUE THREAD

**Issue by day45** [retailcrm/mg-bot-api-client-php#17]
Добрый день. Зависимости на поддерживают php8.0
`❯ composer update                                                                                                                                                              х INT 14:10:30
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - retailcrm/mg-bot-api-client-php[v1.1.8, ..., v1.1.9] require jms/serializer 1.14.* -> satisfiable by jms/serializer[1.14.0, 1.14.1].
    - retailcrm/mg-bot-api-client-php[v1.1.0, ..., v1.1.7] require doctrine/annotations 1.6.* -> found doctrine/annotations[v1.6.0, v1.6.1] but it conflicts with your root composer.json require (1.12).
    - jms/serializer[1.14.0, ..., 1.14.1] require php ^5.5|^7.0 -> your php version (8.0.11) does not satisfy that requirement.
    - Root composer.json requires retailcrm/mg-bot-api-client-php ^1.1 -> satisfiable by retailcrm/mg-bot-api-client-php[v1.1.0, ..., v1.1.9].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
`

**Comment by Neur0toxine** [comment]
Здравствуйте. `mg-bot-api-client-php` пока еще не был обновлен для поддержки PHP 8. Мы зафиксировали задачу и в будущем добавим поддержку PHP 8 - вы узнаете об этом при закрытии issue.
