### ISSUE TITLE
Конфликт с api-client-php 6.0

### ISSUE THREAD

**Issue by day45** [retailcrm/mg-bot-api-client-php#18]
Конфликтует с "retailcrm/api-client-php": "^6.0":
Прописано "doctrine/cache": "1.11.*",
Но без doctrine/cache выше 2.0 клиент RetailCRM выбрасывает исключение:
`Error: Class 'Doctrine\Common\Annotations\PsrCachedReader' not found in ../vendor/retailcrm/api-client-php/src/Builder/FormEncoderBuilder.php:117
Stack trace:
#0 ../vendor/retailcrm/api-client-php/src/Builder/FormEncoderBuilder.php(90): RetailCrm\Api\Builder\FormEncoderBuilder->buildAnnotationReader()
#1 ../vendor/retailcrm/api-client-php/src/Factory/SimpleClientFactory.php(41): RetailCrm\Api\Builder\FormEncoderBuilder->build()
#2 ../components/RetailComponent.php(48): RetailCrm\Api\Factory\SimpleClientFactory::createClient()`

PS: Может дело в doctrine/annotations

**Comment by Neur0toxine** [comment]
Здравствуйте. `api-client-php` не использует `doctrine/cache` т.к. он устарел и более не поддерживается. Для кэширования по умолчанию используется совместимая с PSR-6 реализация - `symfony/cache`.

Судя по возникающей ошибке, вы установили `doctrine/annotations` более старой версии, чем 1.13.x. В версиях ниже 1.13 компонента `PsrCachedReader` действительно нет.

Поэтому пока что установить `api-client-php` версии 6.x и `mg-bot-api-client-php` последней версии нельзя.
